# Generated by Django 2.1.7 on 2020-02-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land_detail',
            fields=[
                ('landid', models.AutoField(primary_key=True, serialize=False)),
                ('lattitude', models.FloatField(max_length=25)),
                ('langitude', models.FloatField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d')),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('no_of_spot', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('price_per_hour', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('verified', models.BooleanField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Land_record',
            fields=[
                ('land_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('total_price', models.IntegerField()),
                ('payment_remaining', models.BooleanField()),
                ('feedback', models.CharField(max_length=255, null=True)),
                ('landid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landlord.Land_detail')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User_detail')),
            ],
        ),
        migrations.AddIndex(
            model_name='land_record',
            index=models.Index(fields=['landid'], name='landid_index'),
        ),
        migrations.AddIndex(
            model_name='land_record',
            index=models.Index(fields=['userid'], name='userid_index'),
        ),
    ]
