# Generated by Django 3.0.1 on 2020-01-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_detail',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
