# Generated by Django 3.0.1 on 2020-01-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_record',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
