# Generated by Django 3.0.1 on 2020-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_detail',
            name='images',
        ),
        migrations.AddField(
            model_name='land_detail',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
