# Generated by Django 3.0.1 on 2020-02-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Location',
            fields=[
                ('Locationid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lattitude', models.FloatField(max_length=25)),
                ('langitude', models.FloatField(max_length=25)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User_detail')),
            ],
        ),
    ]
