# Generated by Django 2.1.7 on 2020-01-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=14)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('role', models.CharField(default='User', max_length=10)),
                ('otp', models.IntegerField(null=True)),
                ('face', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
